// Generated by CoffeeScript 1.7.1

/*
Copyright 2013-2014 Simon Lydell
X11 (“MIT”) Licensed. (See LICENSE.)
 */
var Autoprefixer, autoprefixer;

autoprefixer = require("autoprefixer");

module.exports = Autoprefixer = (function() {
  Autoprefixer.prototype.brunchPlugin = true;

  Autoprefixer.prototype.type = "stylesheet";

  Autoprefixer.prototype.extension = "css";

  Autoprefixer.prototype.defaultEnv = "*";

  function Autoprefixer(config) {
    var browsers, _ref;
    this.config = config;
    browsers = ((_ref = this.config.plugins.autoprefixer) != null ? _ref : {}).browsers;
    this.compiler = autoprefixer.apply(null, browsers);
  }

  Autoprefixer.prototype.optimize = function(_arg, callback) {
    var data, error, map, path, result;
    data = _arg.data, path = _arg.path, map = _arg.map;
    try {
      result = this.compiler.process(data, {
        map: true,
        from: path
      });
    } catch (_error) {
      error = _error;
    }
    return callback(error, {
      data: result.css,
      map: result.map
    });
  };

  return Autoprefixer;

})();
