// Generated by CoffeeScript 1.7.1

/*
 * Copyright 2013-2014 Simon Lydell
 * X11 (“MIT”) Licensed. (See LICENSE.)
 */
var Autoprefixer, autoprefixer;

autoprefixer = require("autoprefixer");

module.exports = Autoprefixer = (function() {
  Autoprefixer.prototype.brunchPlugin = true;

  Autoprefixer.prototype.type = "stylesheet";

  Autoprefixer.prototype.extension = "css";

  Autoprefixer.prototype.defaultEnv = "*";

  function Autoprefixer(config) {
    var browsers, options, _ref, _ref1;
    this.config = config;
    _ref1 = (_ref = this.config.plugins.autoprefixer) != null ? _ref : {}, browsers = _ref1.browsers, options = _ref1.options;
    this.compiler = autoprefixer(browsers, options);
  }

  Autoprefixer.prototype.optimize = function(_arg, callback) {
    var data, error, map, path, result;
    data = _arg.data, path = _arg.path, map = _arg.map;
    try {
      result = this.compiler.process(data, {
        from: path,
        to: path,
        map: {
          prev: map.toJSON(),
          annotation: false
        }
      });
    } catch (_error) {
      error = _error;
      return callback(error);
    }
    return callback(null, {
      data: result.css,
      map: result.map.toJSON()
    });
  };

  return Autoprefixer;

})();
